name: smoke-windows-cygwin-amd64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      # Do a first check out using the system git
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
            fetch-depth: 1
      # Caching (resp. restoring from cache) fails due to Cygwin not wanting
      # dangling symlinks
      #- name: Cache Cygwin installation
      #  id: setup-cygwin
      #  uses: actions/cache@v1
      #  # You need to bust that cache if you want to add a new package or refresh
      #  with:
      #      path: "c:\\tools\\cygwin"
      #      key: cygwin-20191122
      - name: Set up Cygwin
        if: steps.setup-cygwin.outputs.cache-hit != 'true'
        run: |
          choco install cygwin cyg-get sysinternals
          cyg-get cygutils-extra cygwin-devel gcc-core gcc gcc-g++ make cygwin64-w32api-headers binutils libtool git ccache
      - name: Find out environment
        shell: cmd
        run: |
          dir c:\tools\cygwin
          path
      - name: Check out again, using Cygwin git, to reset file permissions
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            git checkout --force
      - name: Output environment
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            c:\tools\cygwin\bin\sh.exe -c "env; pwd; mount; cat /etc/fstab"
      - name: "mount; cat fstab"
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            c:\tools\cygwin\bin\sh.exe -c "mount; cat /etc/fstab"
      - name: id
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            id
      - name: id (low privilege via psexec)
        shell: cmd
        run: |
            path c:\tools\cygwin\bin;C:\ProgramData\chocolatey\lib\sysinternals\tools
            psexec64 -l sh -c "id>/cygdrive/d/a/perl5/perl5/tmp.log"
            type tmp.log
      - name: "Strip/reset permissions"
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            c:\tools\cygwin\bin\sh.exe -c "cd /cygdrive/d/a/perl5/perl5; setfacl -b ."
      - name: Configure
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            c:\tools\cygwin\bin\sh.exe -c "./Configure -des -Dusedevel -Doptimize=-g"
      - name: Build
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            c:\tools\cygwin\bin\sh.exe -c "pwd; echo $PATH; make -j2 test_prep"
      - name: Run unprivileged FS stat tests
        shell: cmd
        run: |
            path d:\a\perl5\perl5;c:\tools\cygwin\bin;C:\ProgramData\chocolatey\lib\sysinternals\tools;c:\windows\system32
            ls -l .
            psexec64 -l sh -c "cd /cygdrive/d/a/perl5/perl5/t; ./perl -I../lib op/stat.t >/cygdrive/d/a/perl5/perl5/tmp.log 2>&1"
            type d:\a\perl5\perl5\tmp.log
            psexec64 -l sh -c "cd /cygdrive/d/a/perl5/perl5/t; ./perl -I../lib ../lib/File/stat.t >/cygdrive/d/a/perl5/perl5/tmp.log 2>&1"
            type d:\a\perl5\perl5\tmp.log
            psexec64 -l sh -c "cd /cygdrive/d/a/perl5/perl5/t; ./perl  -I../lib ../lib/File/Copy.t >/cygdrive/d/a/perl5/perl5/tmp.log 2>&1"
            type d:\a\perl5\perl5\tmp.log
            psexec64 -l sh -c "cd /cygdrive/d/a/perl5/perl5/t; ./perl -I../lib ../cpan/ExtUtils-MakeMaker/t/fixin.t >/cygdrive/d/a/perl5/perl5/tmp.log 2>&1"
            type d:\a\perl5\perl5\tmp.log
      - name: Run Tests
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            path d:\a\perl5\perl5;C:\ProgramData\chocolatey\lib\sysinternals\tools;c:\tools\cygwin\bin
            psexec64 sh -c "make test >./tmp.log 2>&1"
            type tmp.log
