name: smoke-windows-cygwin-amd64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      # Do a first check out using the system git
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
            fetch-depth: 1
      # Caching (resp. restoring from cache) fails due to Cygwin not wanting
      # dangling symlinks
      #- name: Cache Cygwin installation
      #  id: setup-cygwin
      #  uses: actions/cache@v1
      #  # You need to bust that cache if you want to add a new package or refresh
      #  with:
      #      path: "c:\\tools\\cygwin"
      #      key: cygwin-20191122
      - name: Set up Cygwin
        if: steps.setup-cygwin.outputs.cache-hit != 'true'
        run: |
          choco install cygwin cyg-get
          cyg-get cygwin-devel gcc-core gcc gcc-g++ make cygwin64-w32api-headers binutils libtool git ccache
      - name: Find out environment
        shell: cmd
        run: |
          dir c:\tools\cygwin
          path
      - name: Check out again, using Cygwin git, to reset file permissions
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            cd d:\a\perl5\
            git clone perl5 perl5-build
            cd d:\a\perl5\perl5-build
      - name: Output environment
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            cd d:\a\perl5\perl5-build
            c:\tools\cygwin\bin\sh.exe -c "env; pwd; mount; cat /etc/fstab"
      - name: "mount; cat fstab"
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            cd d:\a\perl5\perl5-build
            c:\tools\cygwin\bin\sh.exe -c "mount; cat /etc/fstab"
      - name: "Strip/reset permissions"
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            cd d:\a\perl5\perl5-build
            c:\tools\cygwin\bin\sh.exe -c "cd /cygdrive/d/a/perl5/perl5-build; setfacl -b ."
      - name: Configure
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            cd d:\a\perl5\perl5-build
            c:\tools\cygwin\bin\sh.exe -c "./Configure -des -Dusedevel -Doptimize=-g"
      - name: Build
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            cd d:\a\perl5\perl5-build
            c:\tools\cygwin\bin\sh.exe -c "pwd; echo $PATH; make -j2 test_prep"
      - name: Run Tests
        shell: cmd
        run: |
            path c:\tools\cygwin\bin
            cd d:\a\perl5\perl5-build
            c:\tools\cygwin\bin\sh.exe -c "HARNESS_OPTIONS=j3 make -j3 test_harness"
