name: smoke-windows-msvc100-x86

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
    PERL_SKIP_TTY_TEST: 1

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
            fetch-depth: 10
      - name: Set up MSVC100
        run: |
          choco install vcexpress2010
      - name: Install clcache
        shell: cmd
        run: |
          curl -L https://github.com/frerich/clcache/releases/download/v4.2.0/clcache.4.2.0.nupkg --output clcache.4.2.0.nupkg
          choco install clcache --source=.
      - name: C compiler cache
        id: clcache
        uses: actions/cache@v1
        with:
          path: $HOME\clcache
          key: ${{ runner.os }}-msvc100-x86
      - name: Help
        shell: cmd
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" /help
      - name: Build
        shell: cmd
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
            cd win32
            nmake CCTYPE=MSVC100 WIN64=undef
      - name: Run Tests
        shell: cmd
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
            cd win32
            nmake CCTYPE=MSVC100 WIN64=undef test
