name: smoke-macos-xcode11

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

env:
    PERL_SKIP_TTY_TEST: 1

jobs:
  perl:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
        with:
            fetch-depth: 10
      - name: Configure
        run: |
            export SDK=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
            sh ./Configure -des -Dusedevel
      - name: Build
        run: |
            make -j2
      - name: Run Tests
        run: |
            make -j2 test
